// A group registered with the service
Table groups {
  id int [pk]
  name varchar [unique]
  active boolean [default: true]
  paid_through date [null]
  created_utc datetime [default: 'now()']
}

Table payment_types {
  id int [pk]
  group_id int [ref: > groups.id]
  stripe_token varchar
  created_utc datetime [default: 'now()']
}